apiVersion: v1
appVersion: "test"
version: "v2"
description: A Helm chart for the Aqua Console components
name: server
icon: https://avatars3.githubusercontent.com/u/12783832?s=200&v=4
home: https://www.aquasec.com/
dependencies:
- name: gateway
  version: "6.5.2"
  repository: "https://helm.aquasec.com"
  condition: gateway.enabled
maintainers:
- name: Aqua Security, Inc.
  email: support@aquasec.com
